export enum RoutesEnum {
  CATALOG = '/catalog',
  LOGIN = '/login',
  MANAGEMENT = '/management',
  BRANDS = '/brands',
  CATEGORIES = '/categories',
  COLORS = '/colors',
  CONTACTS = '/contacts',
  MESSENGERS = '/messengers',
  PRICES = '/prices',
  PRODUCTS = '/products',
  ROLES = '/roles',
  SECTIONS = '/sections',
  STORES = '/stores',
  USERS = '/users',
  PROFILE = '/profile',
  FAVORITES = '/favorites',
  SIGNUP = '/signup',
  ADD = '/add',
  EDIT = '/edit',
}
